### ISSUE TITLE
how to get your dataset？

### ISSUE THREAD

**Issue by EzrealLcy** [cakirogluozan/fire-detection#10]
Hello, can you provide the fire data set?

**Comment by cakirogluozan** [comment]
Hello, the labeled dataset is in the following link. It is a bit messy but  I am sure you can extract the information out of it. 

https://drive.google.com/file/d/1xw137EI1oMtmh9_8KFgWuWERCcUtqySJ/view?usp=sharing

PS1. You need to send me a request which I will accept.
PS2. Images are under images folder and labels are in Annotations folder for each tar.gz file.
